### ISSUE TITLE
חלוקת עבודה

### ISSUE THREAD

**Issue by ISHIBubble** [rosenpin/SocialMediaResearch#3]
אישי
- [x] שאלה 2
> - [x] להשלים פירוט בוורד 
> - [x] לפתור בR 
- [x] שאלה 3
> - [x] להשלים פירוט בוורד 
> - [x] לפתור בR 
- [x] סעיף 5
- [x] סעיף 7

תומר
- [x] לסיים שאלה 1
- [x] לעשות את סעיף 4
- [x] לעשות את סעיף 6
- [x] לסיים וורד יפה
- [x] להוסיף תיעוד מסודר 
- [x] להוסיף סטטיסטיקה תאורית 
sd_bigger <- sd(ratio_music_bigger)
sd_smaller <- sd(ratio_music_smaller)
sd_est <- sqrt((sd_bigger*length(ratio_music_bigger)+sd_smaller*length(ratio_music_smaller))/(length(ratio_music_smaller)+length(ratio_music_bigger)-2))
se_est <- sd_est*sqrt(1/length(ratio_music_bigger)+1/length(ratio_music_smaller))

**Comment by ISHIBubble** [comment]
חשוב לשים לב שבשאלות עונים על החלק הראשון גם שנוגע לסטטיסטיקה תאורית

**Comment by rosenpin** [comment]
- [x] להוסיף עבור כל סעיף 
: (1)
סטטיסטיקה תיאורית(מדדים שונים שמתארים את המשתנה;ממוצע, סטיות תקן, גודל המדגם, חלוקה לפי
מגדרוכו'),

**Comment by rosenpin** [comment]
- [ ] גודל אפקט - פקודה שהם רצו
- [ ] לבדוק חי בריבוע לאי תלות בצורה נכונה
